version: '3.7'

services:
  postgresql:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dwh-8
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "127.0.0.1:5432:5432"